drop table if exists test_m cascade 
drop table if exists test_mem cascade 
create table test_m (del_yn boolean, test_no bigint generated by default as identity, name varchar(255), primary key (test_no))
create table test_mem (del_dtm timestamp(6), test_no bigint generated by default as identity, name varchar(255), primary key (test_no))